chore(husky): adiciona verificação de ts erros antes do commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,3 +3,6 @@ npm run format
 
 echo 'Check for linting errors'
 npm run lint || (echo 'Linting errors. Please fix them before commiting.' && exit 1)
+
+echo 'Check for typescript errors'
+npx tsc --noEmit || (echo 'Linting errors. Please fix them before commiting.' && exit 1)
